apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-management-frontend
  labels:
    app: task-management-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-management-frontend
  template:
    metadata:
      labels:
        app: task-management-frontend
    spec:
      containers:
      - name: task-management-frontend
        image: raksha001/devops-task-mgmt-app:task_mgmt_app
        resources:
          limits:
            memory: "100Mi"
        ports:
        - containerPort: 8087

